# Tethys portal_config skeleton
version: 2.0
name:
apps: {}
settings:
  DEBUG: false

  # Baseline; extended at runtime
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1

  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: tethys_platform
      USER: tethys_default
      # Injected at runtime
      HOST: postgres
      PORT: 5432
      CONN_MAX_AGE: 0

  CHANNEL_LAYERS:
    default:
      # In-memory layer
      BACKEND: channels.layers.InMemoryChannelLayer

  TETHYS_PORTAL_CONFIG:
    ENABLE_OPEN_PORTAL: true
    BYPASS_TETHYS_HOME_PAGE: true

# Site / branding content
site_settings:
  GENERAL_SETTINGS:
    SITE_TITLE:
    BRAND_TEXT:
